image:
  file: .gitpod.Dockerfile

tasks:
  - init: go get && go build ./... && go test ./... && make
    command: echo "Golang OK!"
  - init: echo "create database prom;" | mysql > /dev/null 2>&1
    command: echo "MySQL OK!"
