image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      go get ./... && \
      go build ./cmd/prometheus_sql_adapter && \
      go test ./... && \
      make && \
      (echo "create database prom;" | mysql > /dev/null 2>&1)
