---
version: '3.7'

services:
  prometheus_sql_adapter:
    container_name: prometheus_sql_adapter
    hostname: prometheus_sql_adapter
    build:
      context: ./
    restart: always
    command:
      - '--listen'
      - '0.0.0.0:8080'
      - '--db'
      - 'mysql://root:root@mysql:3306/db'
    volumes:
      - './data/:/var/lib/sqlite/'
    expose:
     - '8080'
    environment:
      - 'RUST_BACKTRACE=full'
      - 'RUST_LOG=error'
    networks:
      - local-link
      - planet-link
    logging:
      driver: "json-file"
      options:
        max-file: '4'
        max-size: '250m'

  mysql:
    container_name: 'prometheus_sql_adapter_mysql'
    hostname: 'prometheus_sql_adapter_mysql'
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=db'
      - 'MYSQL_USER=prom'
      - 'MYSQL_PASS=prom'
    volumes:
      - './data/mysql:/var/lib/mysql/'
    networks:
      - local-link
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  mysql-mon:
    container_name: 'prometheus_sql_adapter_mysql-mon'
    hostname: 'prometheus_sql_adapter_mysql-mon'
    image: prom/mysqld-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: 'root:root@(mysql:3306)/'
    expose:
      - 9104
    networks:
      - local-link
      - planet-link
    depends_on:
      - mysql
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

# networks
networks:
  local-link:
    external: false
  planet-link:
    external: true
