---
version: '3.7'

services:
  adapter:
    container_name: prometheus_sql_adapter
    hostname: prometheus_sql_adapter
    build:
      context: ./
    restart: always
    command:
      - '--listen'
      - '0.0.0.0:8080'
      - '--db'
      - 'mysql://prom:prom@tcp(localhost:3306)/prom'
#      - 'sqlite://file:/var/lib/sqlite/prometheus.db?cache=shared&mode=rwc'
    volumes:
      - './data/sqlite/:/var/lib/sqlite/'
    depends_on:
      - mysql
    expose:
     - '8080'
    logging:
      driver: "json-file"
      options:
        max-file: '4'
        max-size: '250m'

  mysql:
    container_name: 'prometheus_sql_adapter_mysql'
    hostname: 'prometheus_sql_adapter_mysql'
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=prom'
      - 'MYSQL_USER=prom'
      - 'MYSQL_PASS=prom'
    volumes:
      - './data/mysql:/var/lib/mysql/'
    network_mode: 'host'
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

networks: {}